lib/agent/actions.js, lib/agent/cli.js, lib/agent/hooks.js, lib/agent/plugins/control-panel/api/accounts.js, lib/agent/plugins/control-panel/index.js, lib/agent/plugins/control-panel/sender.js, lib/agent/providers.js, lib/agent/transports/http/index.js, lib/agent/triggers/power/index.js, lib/plugins.js, package.json
Originally (#122) from @tomas
The most important fixes are:
- Ensures all returns in cli.js are nested inside functions (otherwise it's invalid JS syntax).
- Handle a race condition in the fire_callbacks part in agent/providers, that would provoke a specific caller not to get a callback when waiting for a provider.
- Updates the triggers module to 0.0.3, which fixes battery detection on Linux.
- Waits a sec before checking battery status on the 'state_changed' event, that in some cases provoked the power triggers to be fired multiple times.
- Passes a callback to the load_api export in the CP's index.js, that allows passing keys to the api.keys.set() function.
=> Syntax and fixes 2

lib/agent/plugins/control-panel/api/request.js, lib/agent/plugins/control-panel/long-polling/index.js, lib/agent/plugins/control-panel/long-polling/test/index_spec.js, lib/agent/plugins/control-panel/setup.js, lib/system/index.js
Until now user-agent used when sending request to the control panel were inconsistent both in the different parts of the Prey node client and with the rest of the Prey clients. This PR fixes that.
=> Fix user agent

lib/agent/plugins/control-panel/index.js
=> Fix graceful shutdown after initial config

lib/agent/plugins/control-panel/setup.js, lib/agent/providers/hardware/windows.js
This pull request fixes both Windows and Mac bug detecting the device type when configuring Prey
=> Fix laptop desktop detection

lib/package.js, test/lib/package.js
PR created for the new node releases url on google storage.
=> Node releases url storage

lib/agent/plugins/control-panel/api/request.js, lib/agent/utils/storage.js
Created to cover up the case when the user sign up into prey on the installation suit. In the last release there was an issue when the api key wasn't defined yet.
=> Fix apikey undefined case

lib/agent/actions/fileretrieval/index.js, lib/agent/actions/fileretrieval/storage.js, lib/agent/actions/geofencing/storage.js, lib/agent/plugins/control-panel/long-polling/index.js, lib/agent/utils/storage.js, package.json
Adjust deleting commands from local database based on sqlite.
=> Storage logic improvement

lib/agent/actions/wipe/windows/index.js, lib/agent/actions/wipe/wipe.js
Allows to delete local files from OneDrive for Personal and Business accounts
=> OneDrive local files wipe

lib/agent/providers/geo/win32/index.js
There's a fix that force to re-scan the wi-fi networks on windows but in some cases the logic won't allow to reach that line of code. For this PR that fix is forced to occur.
=> Force networks re-scan fix

npm-shrinkwrap.json, package.json
Replace the linus library to include the openSUSE distro case
=> Add opensuse distro case

lib/agent/providers/hardware/windows.js
Ram size on windows fix, from KB to MB.
=> Ram size on windows fix

lib/agent/actions/wipe/index.js, lib/agent/providers/webcam/windows/index.js, lib/agent/triggers/location/index.js, test/lib/agent/providers/geo/wifi_strategy.js
Fixes:
- New location event trigger
- Webcam photo on windows
- No user logged case on wipe
=> Location, webcam and wipe fixes

npm-shrinkwrap.json
Child process fix on satan library that causes less hardware information.
=> Ubuntu fixed hardware info

lib/agent/triggers/location/index.js
Improve the callbacks handling on the location watcher.
=> Location callbacks handling

lib/agent/providers/network/windows.js
Force networks scanning before getting the closest access points.
=> Force networks scan on windows

lib/agent/actions/alarm/windows.js, lib/agent/plugins/control-panel/long-polling/index.js, lib/agent/providers/network/index.js, lib/agent/triggers/auto-connect/index.js, lib/agent/triggers/connection/index.js, lib/system/index.js, npm-shrinkwrap.json, package.json
- Check internet connection instead of making a request to solid.preyproject.com
- Fix to voladjust.exe name and new wipe logic options.
- Add missing dependencies
=> Connection state fix + 2 action fixes

CHANGELOG.md, lib/agent/triggers/auto-connect/reconnect.js, lib/agent/triggers/connection/index.js, lib/agent/triggers/location/index.js
- Improve check when locations are similar comparing accuracy.
- Check with control panel on connection status change
=> Improve check on connection and similar locations

lib/agent/actions/fileretrieval/index.js, lib/agent/plugins/control-panel/api/devices.js, lib/agent/plugins/control-panel/api/push.js, lib/agent/triggers/auto-connect/reconnect.js, lib/agent/triggers/control-zones/index.js, lib/exceptions.js, lib/package.js
All post requests to api as json.
=> Post request to api as json

CHANGELOG.md, lib/agent/plugins/control-panel/secure.js, lib/system/linux/index.js, lib/system/mac/index.js, npm-shrinkwrap.json, package.json
- Fix browser open on linux for sso.
- Update windows service updater
=> Linux sso mac address fix

CHANGELOG.md, lib/conf/panel/index.js, lib/package.js
- Fix issue when device key exists but is not valid.
- Also limits older prey version deletion to windows for now.
=> SSO on invalid keys fix

lib/agent/plugins/control-panel/api/push.js, lib/agent/plugins/control-panel/api/test/push_spec.js, lib/agent/triggers/control-zones/index.js, lib/package.js
- Post requests as url-enconded for now except for events.
- Fix status header object.
=> Revert push as json and specs

CHANGELOG.md, lib/agent/actions/geofencing/index.js, test/lib/agent/actions/geofencing.js
- Geofencing start event sent only when the device has been added to a zone.
=> Restore geofencing start

lib/agent/actions/cypher/index.js, npm-shrinkwrap.json, package.json
New cypher binaries for production
=> Cypher fixes

lib/agent/providers/geo/strategies.js, lib/agent/providers/network/windows.js, test/lib/agent/providers/geo/wifi_strategy.js
This PR includes:
- Proxy for location request on wifi strategy.
- Addition of device keys on header request.
- Fix for Windows wifi networks scan for german language
=> WIP: Add proxy for location service

lib/agent/plugins/control-panel/long-polling/index.js, lib/agent/plugins/control-panel/long-polling/test/index_spec.js, lib/agent/triggers/connection/index.js, lib/agent/triggers/hostname/index.js, lib/agent/triggers/power/index.js, npm-shrinkwrap.json, package.json
- Check connection status only when there's a network status change.
- Device hostname updating fix
- On power change abort long-polling current request
=> Connection trigger improvements

lib/agent/plugins/control-panel/long-polling/index.js, lib/agent/providers/network/index.js, lib/agent/providers/network/linux.js, lib/agent/providers/network/mac.js, lib/agent/providers/network/windows.js, lib/agent/triggers/connection/index.js, lib/agent/triggers/network/index.js, lib/agent/triggers/power/index.js, lib/agent/triggers/status/index.js, lib/system/linux/index.js
Improvements on active access point obtaining, avoiding scan all the access points to get the current one.
It also improves online-offline data management.
=> Current AP scan modified

lib/agent/plugins/control-panel/long-polling/index.js, lib/agent/providers/files/index.js, lib/agent/providers/files/tree.js, lib/agent/providers/network/linux.js, lib/agent/providers/network/windows.js, lib/agent/providers/webcam/mac/index.js, lib/agent/updater.js, lib/package.js
This PR includes:
- Workaround for windows active access point obtaining
- Files list parsing error coverage
- Fix for webcam provider on Catalina macOS version
=> Changes performance check

lib/agent/commands.js, lib/agent/plugins/control-panel/index.js, lib/agent/updater.js, lib/agent/utils/storage.js
- Show client update error on prey.log file
- Store report command on local database
- For status request check if device is already stolen before re-launching the command
=> Store report command and check already stolen

lib/agent/hooks.js, lib/agent/plugins/control-panel/api/keys.js, lib/agent/plugins/control-panel/index.js, lib/agent/providers/network/index.js, lib/agent/providers/network/linux.js, lib/agent/providers/webcam/windows/index.js, lib/agent/triggers/connection/index.js, lib/agent/triggers/network/index.js, lib/agent/triggers/power/index.js, lib/conf/panel/index.js, tools/build.sh
When the connection status is "disconnected" the device retries getting the status again with time intervals, until the state is "connected" again.
=> Connection status check retry and verify status changed

lib/agent/actions/logretrieval/index.js, npm-shrinkwrap.json, package.json, test/lib/agent/actions/logretrieval.js
Log retrieval action for support purposes.
Attaches prey.log, prey.conf and commands.db files
=> Logretrieval action

lib/agent/providers/screenshot/index.js, lib/agent/providers/screenshot/linux/index.js, lib/agent/providers/screenshot/mac/index.js, lib/agent/providers/screenshot/windows/index.js, lib/agent/providers/webcam-extra/index.js, lib/agent/providers/webcam/index.js, lib/agent/providers/webcam/linux/index.js, lib/agent/providers/webcam/mac/index.js, lib/agent/providers/webcam/windows/index.js, lib/agent/reports/stolen.js
- Camera and Screenshot fixes for macOS
- Secondary camera photo management
=> Camera and Screenshot fixes and improvements

CHANGELOG.md, lib/agent/providers/network/windows.js, lib/agent/providers/webcam/linux/index.js, lib/agent/providers/webcam/windows/index.js, lib/agent/triggers/hostname/index.js, lib/conf/cli.js, lib/conf/tasks/index.js, lib/system/windows/paths.js, test/lib/agent/triggers/hostname.js
Make sure device renamed event is send when there's internet connection
=> Device rename event fix

lib/agent/actions/geofencing/index.js, lib/agent/actions/logretrieval/index.js, lib/agent/providers/screenshot/index.js, lib/agent/providers/webcam/windows/index.js, lib/agent/reports.js, lib/system/windows/index.js, test/lib/agent/actions/logretrieval.js
Fixes and changes:
* Case on no local stored geofences
* Fix on logretrieval compressed file extension
* Fix on screenshot when no logged user found
* Fix on webcam when preyshot fails
* Delete extra_attachment log error
* Find logged user retry on windows
=> Fix picture and logged user retry for windows

lib/package.js, npm-shrinkwrap.json, package.json
Device architecture recognition fixed for update
=> Update with corresponding arch

lib/agent/actions/wipe/index.js, lib/system/index.js, test/lib/agent/actions/wipe.js
* Fix for windows when there's no administrator service
* Copy windows updater inside /bin
=> Fix for wipe on win7 and service updater on bin dir

CHANGELOG.md, npm-shrinkwrap.json, package.json
Version update on package.json and npmshrinkwrap.json
Changelog added for new version
=> Add version 1.9.10 to package.json

lib/agent/actions.js
the action "stop" did not send the messageID and this generated an infinite loop, it was corrected and now if it is sending
=> Include messageID on stopped action response

CHANGELOG.md, lib/agent/utils/storage.js
validates if the table keys exists in the recovery of the old db
=> validates if the table keys exists in the recovery of the old db

lib/agent/plugins/control-panel/long-polling/index.js, lib/agent/plugins/control-panel/long-polling/test/index_spec.js, lib/agent/providers.js, lib/agent/providers/geo/darwin/index.js, lib/agent/providers/geo/strategies.js, lib/agent/utils/storage.js
with this change the connection with the panel is repaired when starting the client
=> Fix startup connection

lib/agent/actions/logretrieval/index.js, test/lib/agent/actions/logretrieval.js
Add winsvc.log and updater.log to Windows logretrieval action
=> Add windows service logs to logretrieval

lib/agent/plugins/control-panel/secure.js, openwebbrowser.sh
Fix for ubuntu installation. It fixes the problem on Firefox when opening Firefox web browser.
Description of the problem: opening a new web browser when an instance of firefox is already running caused an error.
=> fix ubuntu installation

lib/agent/actions/geofencing/index.js
fix geofencing if cb is a function
=> fix geofencing

lib/agent/plugins/control-panel/index.js, lib/agent/providers/hardware/index.js
fix
dont send information to panel ( os_edition , tpmmodule and winsvc
=> fix send information from service windows ( tpm_module, os_edition, winsvc_version, rp_module) to panel

lib/package.js
Added 'device key' header when doing GET request to Prey's lastest version
=> added device key header

lib/conf/tasks/index.js
HTTP request to WinSVC when updating (when calling 'config activate' on new downloaded version).
=> feature: call to winsvc when updating

package-lock.json, package.json
https://github.com/prey/prey-node-client/security/dependabot/19
=> new version eslint 8.44.0 to correct json5 library dependency

package-lock.json, package.json
https://github.com/prey/prey-node-client/security/dependabot/12
=> new version async v2.6.4 or above

package-lock.json, package.json
https://github.com/prey/prey-node-client/security/dependabot/22
=> new sqlite version

package-lock.json, package.json
https://github.com/prey/prey-node-client/security/dependabot/26
=> new semver version 7.5.2 or above

lib/agent/actions/triggers/index.js, lib/agent/commands.js
Fix non persisting action when triggers and same type action is already executed
=> Fix non persisting action triggers and same type action is already executed

CHANGELOG.md
fix on wipe explanation of changes
=> docs: fix on redaction of changelog

lib/agent/control-panel/index.js, lib/agent/triggers/location/index.js, test/lib/agent/triggers/location.js
location aware was not getting new location
=> fix: Fix on location aware

lib/agent/actions/osquery/index.js
=> validate osquery action args
