- lib/agent/actions/wipe/windows.js
Windows Vista (>=6.0) introduced the AppData folder, while 2003 and below (<=5.2) used Application Data. Thus, it seems like these two lines should be swapped.
> Windows AppData paths correction in wipe

- lib/agent/helpers.js
- lib/agent/plugins/control-panel/api/request.js
- lib/agent/plugins/control-panel/interval/test/interval_spec.js
- npm-shrinkwrap.json
- test/lib/agent/helpers.js
- test/shrinkwrap_spec.js
This fixes a big issue I introduced in 1.4.0 that prevented said version from creating the `current` symlink and hence starting the client.
Pending:
> Update npm-shrinkwrap to include semver

- lib/agent/commands.js
- lib/agent/plugins/control-panel/index.js
- lib/agent/plugins/control-panel/test/main_load.js
- test/lib/agent/commands.js
This PR adds the following:
- The report command is persisted when the command signature is something like `{command: 'get', target: 'report', options: {interval: 5, exclude: ['picture']}}`.
- Control-panel plugin now takes into consideration the exclusions (picture and/or screenshot) when receiving missing instructions through the `status.json` end-point.
> Command persistence. fix #133, fix #127

- lib/agent/plugins/control-panel/api/request.js
- lib/agent/plugins/control-panel/long-polling/index.js
- lib/agent/plugins/control-panel/long-polling/test/index_spec.js
- lib/agent/providers/network/index.js
- lib/agent/triggers/connection/index.js
Right now, the long-polling logic is not taking the `try_proxy` config into consideration. This PR fixes that, but at the cost of having to handle the whole request from the `long-polling` module instead of using the `api.devices.get.commands` and `api.request` modules, which also brings a little bit of logic repetition.
This is how the logic works now.
- if proxy
- try connecting with proxy, on failure cancel request
- if failed
- abort request and retry without proxy
- if non-proxied request fails
- abort request and re-schedule request with 3 seconds timeout
- else
- execute commands if any and re-schedule request
- else
- execute commands if any and re-schedule request
- else
- connect without proxy
- if failed
- abort request and re-schedule request with 3 seconds timeout
- else
- …
> Fix long polling with proxy

- lib/agent/plugins/control-panel/long-polling/index.js
- lib/agent/providers/network/index.js
If there are more than 4 consecutive instant reponses from the server with status code `200`, it adds a 5 seconds delay between requests. This, as a strategy for the possibility that the server is not using long-polling (ie. development, staging environments or custom servers).
> Change long-polling strategy to 5secs interval strategy on 5+ instant responses

- lib/agent/actions/fileretrieval/index.js
- lib/agent/actions/fileretrieval/storage.js
- lib/agent/actions/fileretrieval/upload.js
- lib/agent/plugins/control-panel/api/push.js
- lib/agent/providers/files/tree.js
Handling with an issue related to the access permissions for the user 'prey' to all the device folders, it was solved using the run_as_user function.
Also fixed another issue for the win-attr package in linux.
> Filebrowser permissions

- lib/system/index.js
This PR fixes a problem setting requests' user-agent, because node's os.release() function returns a wrong OSX version.
> Use correct OS version on user-agent

- lib/conf/tasks/daemon.js
PR created in order to fix the issue https://github.com/prey/prey-node-client/issues/58
Several users reported errors during Prey installation on Windows, most of them with local language beyond latin alphabet. The error can be seen in the prey-install-log:
The proposed solution is to change the default codepage during the installation process to '65001' (UTF-8). After this fix in the prey-install.log:
And finally installation process works properly.
> Ensure UTF-8 codepage on prey install (Error 1603)

- lib/agent/actions/wipe/windows.js
- lib/agent/actions/wipe/wipe.js
- test/lib/agent/actions/wipe.js
Using email wipe action there was a chance that all the email information can be recovered because the Outlook and Thunderbird profiles were still available.
This PR makes sure that all the data is erased.
Given that, without a profile, Firefox and Thunderbird crashes when trying to open after wiping Cookies or Emails respectively, a logic was added to create a new default profile.
Also in windows the use of taskkill command to close all programs before wiping.
> Remove Mail profiles data

- lib/agent/actions/fileretrieval/storage.js
- lib/agent/commands.js
- lib/agent/utils/storage.js
- test/lib/agent/utils/storage.js
In this PR the command storage logic is modified to use sqlite, creating a special table for pending commands and another for uploading files.
The goal of these changes is to avoid the previous corruption of the original command file when the pc is shutted down in the hard way, and keep a most organized set of commands in the file.
> Commands handle using sqlite

- lib/agent/actions/geofencing/index.js
- lib/agent/actions/wipe/linux.js
- lib/agent/actions/wipe/mac.js
- lib/agent/actions/wipe/windows.js
- lib/agent/actions/wipe/wipe.js
New feature added to the wipe action. It deletes the local data from Dropbox and Google Drive without affecting the account online.
First the Dropbox/Drive processes are killed, then the configuration files are wiped out followed for the files in the respective directories.
> Delete local cloud files

- lib/agent/actions.js
- lib/agent/plugins/control-panel/long-polling/index.js
- lib/agent/plugins/control-panel/sender.js
Modify logic for received actions if there's a messageID included. Also covering the case for the "\n" command error (Command Undefined in the prey log).
> Bridge on node client

- lib/agent/actions/fileretrieval/index.js
- lib/agent/actions/fileretrieval/storage.js
- lib/agent/actions/fileretrieval/upload.js
There was an issue for the file resuming after the client disconnection, after reconnecting if the request still exists the file upload continued so there's no need to use the logic implemented for resuming.
In this PR the file state is always verified and it takes action with that information, deleting the file db registry if the file it's completed or cancelled.
> Files upload resuming

- lib/conf/gui/linux/prey-config.py
- lib/conf/gui/mac/PreyConfig.app/Contents/MacOS/prey-config.py
Users with mails with too many characters after de '.' (Ex: hi@company.success) weren't able to signup to prey on mac and linux. This PR fixes that problem extending the maximum number of characters from 4 to 7.
> Signup mail maximum characters number change

- lib/agent/utils/storage.js
- lib/conf/install.js
- lib/package.js
Upgrade logic modified:
- The download package is not gonna be deleted and it's gonna be used again when the retry occurs.
- After 3 upgrade failed attempts the client it's gonna send an event to the control panel and the client it's not gonna try to upgrade again.
- When the upgrade is succeeded the success event it's also sent.
> Client update retry

- lib/agent/actions/wipe/index.js
Windows wipe on 'Not logged user' error
> Wipe action without user logged in

- lib/agent/actions/geofencing/storage.js
- lib/agent/triggers/geofencing/index.js
- lib/agent/utils/keys-storage.js
- lib/agent/utils/storage.js
- test/lib/agent/triggers/geofencing.js
This PR introduces new logic for the location change detection used in geofencing.
When the wifi location succeeded the mac address it's saved in the local storage and when it detects a new mac address the registry it's updated. When the device it's connected to a new mac address the client looks for the location and checks if zones states changed and notifies if that's the case.
The mac address it's checked every 3 minutes.
> Geofencing mac address check

- lib/agent/actions/alarm/index.js
If it's there an error when the alarm action finishes the volume raise every one second doesn't stop. This PR include that specific case.
> Alarm volume raise fix

- lib/agent/providers/network/windows.js
The devices using cyrillic alphabet can't recognise the nearest access points because the command that get that info returns characters unrecognisable for the client.
This PR changes the charset before running the command.
> Location fix for cyrillic alphabet

- lib/agent/triggers/geofencing/index.js
- lib/agent/utils/storage.js
Every time the client save a a command, geofence, file, etc, it checks if the key already exists before store it, doesn't save it if that's the case to prevent replication in the db.
> Local database duplications fix

- lib/agent/updater.js
- lib/conf/install.js
- lib/package.js
Fixes for the success update event:
- Now it's sent after the client reboots.
- The local registry includes the old version also.
- After the event it's sent, the local table 'versions' it's cleared.
> Update success event modified to be sent after the client reloads

- lib/agent/utils/storage.js
If the command already exists in the db, instead of cancel the saving it replaces the stored one.
> Replace command in local db

- lib/agent/providers/webcam/windows/index.js
In case the prey-webcam.exe fails taking the picture for the report, it's gonna be try again with snapshot.exe
> Windows report picture retry

- CHANGELOG.md
- lib/agent/providers/hardware/linux.js
On linux when a device_type is different from Laptop, Desktop or Tablet (for example on a virtual machine the device type is 'Other') it assigns the Laptop type.
> 'Other' device type fix for linux

- CHANGELOG.md
- lib/system/windows/index.js
After the callback is received, the complete network scanning has couple of seconds delay. This way we ensure the networks are totally scanned before the client asks for the nearest access points.
> Timeout on scan networks callback

- lib/agent/actions/wipe/index.js
- lib/agent/actions/wipe/runner.js
- lib/agent/actions/wipe/wipe.js
- lib/system/index.js
- lib/system/linux/index.js
- lib/system/mac/index.js
- lib/system/windows/index.js
Allow to wipe files from any user account no matter the privileges of the logged user.
> Wipe as admin user

- lib/agent/plugins/control-panel/api/devices.js
- lib/agent/triggers/location/index.js
- npm-shrinkwrap.json
- package.json
- test/lib/agent/triggers/location.js
Check location aware setting with the /status.json endpint instead of sending empty location data {}
> Check location setting through status.json endpoint

- lib/agent/providers/files/index.js
- lib/agent/providers/files/tree.js
File scanning fix for fileretrieval. After node version update the initial scanned directory was C:\Windows\system32 instead of C:\
> Fix file scanning on windows

- lib/agent/index.js
- lib/agent/plugins/control-panel/long-polling/index.js
- lib/agent/triggers/location/index.js
- lib/agent/updater.js
- lib/package.js
- test/helpers.js
- test/lib/agent/providers/geo/wifi_strategy.js
- test/lib/agent/updating_spec.js
- test/lib/package.js
This PR includes:
- Client version update reformulation. The client is gonna check for updates when it receives a response for the long-polling request, waiting 3 hours for the next attempt.
- It improves the errors detection into the upgrade process and notifies on every failed or success attempt
- Deletes old client versions keeping the last 2.
> Autoupdate improvements

- lib/agent/actions/triggers/index.js
- lib/agent/commands.js
- lib/agent/plugins/control-panel/api/devices.js
- lib/agent/plugins/control-panel/api/test/post_missing_spec.js
- lib/conf/cli.js
- test/lib/agent/commands.js
Automation command to set device as missing or recovered from the node client.
> Set as missing command for automations

- lib/agent/updater.js
- lib/conf/install.js
- lib/package.js
- test/lib/agent/updating_spec.js
Upgrade targets available:
- Reset: Deletes the current attempts for autoupdate
- Restart: Kill the client process so it can start again
- Activate: Activates a given client version and restart it
- Delete: Deletes a given client version and restart it
> Upgrade command improvements

- lib/agent/providers.js
- lib/agent/providers/indicators/index.js
solved the problem of consulting every three minutes when there is no battery
> battery check when writing to log

- lib/agent/providers/encryption-keys/index.js
- lib/agent/providers/encryption-status/index.js
- test/lib/agent/providers/encryption-keys.js
- test/lib/agent/providers/encryption-status.js
Solve issue when the encryption status info has the wrong format, this causes a client critical error
> Manage encryption status info error

- lib/system/windows/index.js
- npm-shrinkwrap.json
- package.json
get os edition for windows 11 with library systeminformation
> get os edition for windows 11

- lib/agent/providers/geo/darwin/index.js
This is the fix for mac native accuracy when it gives too many digits after dot in that float number.
> Fix panel mac native accuracy location

- lib/agent/actions/alert/index.js
> Fixs alert problem when message is not a string

- lib/agent/actions/triggers/index.js
- lib/agent/commands.js
- lib/agent/common.js
- lib/agent/hooks.js
- lib/agent/providers/hardware/index.js
- lib/agent/reports/specs.js
- lib/agent/triggers.js
Currently this action is removing all triggers once a new trigger is added to some device. this PR fixes this bug and includes some improvements:
- a major code refactor in the triggers.js file
- before adding or updating each trigger, check if the incoming triggers already exist in the local database to remove outdated data or add new ones.
-The last point also covers the case of trying to insert a duplicate trigger, causing an error and blocking the execution of the process.
> Fix triggers action

- lib/agent/triggers/status/index.js
- test/lib/agent/triggers/status.js
Get status function now accepts more than one callback and if callback stack have more than 5 cb then it returns null and if get_status takes more than 5 minutes, also returns null.
> Get status function now accepts more than one callback

- lib/agent/plugins/control-panel/secure.js
fix on the double assignment of api key on prey conf
> fix: Remove the double api key on fresh install

- lib/agent/socket/listeners.js
permissions in macos needed to send the name of the event in the payload to api.
> fix: fix to api push event for permisions in macos
